apiVersion: v1
kind: Service
metadata:
  name: reddit-app-service
spec:
  type: NodePort
  selector:
    app: reddit-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30007