apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-app
  template:
    metadata:
      labels:
        app: reddit-app
    spec:
      containers:
      - name: reddit-app
        image: us-west2-docker.pkg.dev/reddit-gcp/reddit-repo/reddit-app:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"